### ISSUE TITLE
Misuse of :FOR[AntennaRange] in patches.

### ISSUE THREAD

**Issue by DanStaal** [linuxgurugamer/AntennaRangePatches#1]
All the patches in this pack use ':FOR[AntennaRange]' (apply unconditionally, apply other patches requiring the 'AntennaRange' mod apply) instead of ':NEEDS[AntennaRange]'.  (Apply only in the presence of a folder, DLL , or ':FOR' indicating the presence of AntennaRange.)

**Comment by linuxgurugamer** [comment]
updated, thank you
